/* Generated by RuntimeBrowser.
 */
#import "SSRequestDelegate.h"
#import "SSAuthenticateRequest.h"
#import "SSAuthenticateResponse.h"

@protocol SSAuthenticateRequestDelegate <SSRequestDelegate>

@optional

- (void)authenticateRequest:(SSAuthenticateResponse *)arg1 didReceiveResponse:(SSAuthenticateResponse *)arg2;
//- (void)authenticateRequest:(SSAuthenticateRequest *)arg1 didReceiveResponse:(SSAuthenticateResponse *)arg2;

@end
